language: python

services:
  - docker

stages:
  - docker_image_unit_test
  - docker_image_tag_and_push
  - name: do_unit_test_from_docker_hub_image
    if: branch = master

jobs:
  include:
    - stage: docker_image_unit_test
      script: 
        - docker --version
        - mkdir -p server/config
        - touch server/config/settings.cfg
        - echo "CLIENT_SECRET=''" >  server/config/settings.cfg
        - docker build -t amazeteam/cmpe272project -f docker/Dockerfile .
        - echo "CLIENT_SECRET='$AUTHO_CLIENT_SECRET'" > server/config/settings.cfg
        - docker run --rm -v `pwd`/server/config:/root/app/server/config  amazeteam/cmpe272project unittest

    - stage: docker_image_tag_and_push
      script: 
        - docker --version
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
        - mkdir -p server/config
        - touch server/config/settings.cfg
        - echo "CLIENT_SECRET=''" > server/config/settings.cfg
        - docker build -t amazeteam/cmpe272project:$TAG -f docker/Dockerfile .
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker push amazeteam/cmpe272project:$TAG
        - docker logout

    - stage: do_unit_test_from_docker_hub_image
      script:
        - docker --version
        - mkdir -p server/config
        - touch server/config/settings.cfg
        - echo "CLIENT_SECRET='$AUTHO_CLIENT_SECRET'" > server/config/settings.cfg
        - docker run --rm -v `pwd`/server/config:/root/app/server/config amazeteam/cmpe272project  unittest



